### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by aminone** [abbas-oveissi/generator-helma-mvp#3]
من این خطا رو گرفتم
```
$ yo helma-mvp
/usr/lib/node_modules/generator-helma-mvp/generators/util.js:39
  let otherwiseLineIndex = -1;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-helma-mvp/generators/app/index.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by abbas-oveissi** [comment]
من از نود نسخه‌ی 7.7.4 استفاده میکنم، شاید اگر شما هم آپدیت کنید مشکل حل بشه

**Comment by aminone** [comment]
درسته مشکل ازنسخه نود من بود خیلی قدیمی بود. با آپدیت حل شد
